[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[fuzz]
# The number of fuzz runs for fuzz tests
runs = 5
[invariant]
runs = 5

# See more config options https://github.com/foundry-rs/foundry/tree/master/config